### ISSUE TITLE
Works on firefox esr?

### ISSUE THREAD

**Issue by Janaue** [jscher2000/dont-accept-webp#1]
hello

I tried this addon on stock firefox ESR but this picture is shown as webp
https://upload.wikimedia.org/wikipedia/commons/a/a1/Johnrogershousemay2020.webp

is this normal?

**Comment by BMWBig6** [comment]
I have noticed in the past month or so, the webp override doesn't seem to work anymore.  Something must have changed (either with Firefox, the servers, or the plugin?).

**Comment by jscher2000** [comment]
> I tried this addon on stock firefox ESR but this picture is shown as webp
> https://upload.wikimedia.org/wikipedia/commons/a/a1/Johnrogershousemay2020.webp
> 
> is this normal?

Yes. The extension cannot change the format of the images sent by the server, so if the native format is WebP, you will get WebP. What the extension does is discourage servers from encoding JPEG and PNG images as WebP. For example, the server normally will send Firefox WebP for this image:

https://i2.wp.com/radical-mag.com/wp-content/uploads/2019/08/@Test-BMW-320d-8.jpg

But if you enable the extension, you get an actual JPEG.

**Comment by jscher2000** [comment]
> I have noticed in the past month or so, the webp override doesn't seem to work anymore. Something must have changed (either with Firefox, the servers, or the plugin?).

Any difference if you toggle the toolbar button? The yellow triangle indicates sending the native Accept header, and the gray octagon indicates removing image/webp from the Accept header. 

If you don't see the button, check the Overflow menu near the right end of the toolbar (>>).

If it's not there, make sure the extension is enabled on the Add-ons page. 

If it's enabled, check the Customize tab to see whether it needs to be added to the bar. See: [Customize Firefox controls, buttons and toolbars](https://support.mozilla.org/kb/customize-firefox-controls-buttons-and-toolbars).

If it's nowhere to be found, and you are using private windows, make sure to enable the extension for private windows (on the Add-ons page, click the extension title to open the Details tab, scroll down to settings and allow in private windows).

**Comment by BMWBig6** [comment]
I do have the gray button (and toggled it just to verify).  The webp images that I am seeing the most are from Google image search results (which I think are cached/hosted on Google servers).

**Comment by jscher2000** [comment]
>  The webp images that I am seeing the most are from Google image search results (which I think are cached/hosted on Google servers).

I thought Google didn't store the full-sized images (for copyright reasons), but you should be able to tell from the URLs. If there is a sample search you want to share, that might be helpful.

**Comment by BMWBig6** [comment]
Here is an example:  https://www.google.com/search?q=dragonflite 95&tbm=isch&tbs=isz:l

Check out the image search results (thumbnails) hosted by radiosailing.net, which if you save or drag/drop will create a .JPG (presumably due to using your plugin).  However, if I open the file, my image viewer says it's actually a .webp file.

**Comment by jscher2000** [comment]
> Here is an example: (https://www.google.com/search?q=dragonflite+95&tbm=isch&tbs=isz:l)
> 
> Check out the image search results (thumbnails) hosted by radiosailing.net, which if you save or drag/drop will create a .JPG (presumably due to using your plugin). However, if I open the file, my image viewer says it's actually a .webp file.

Hmm, yes, I see, [the one hosted on Shopify](https://cdn.shopify.com/s/files/1/1075/6524/products/DF95_Complete_with_A_Rig.jpg?v=1458355119) has discrepant behavior for drag and drop. 

When you save an image from a page, Firefox usually re-requests it from the server. Testing with that image, I see these inconsistencies in Firefox's behavior for the requests:

(1) right-click > Save Image As (or Shift+right-click to override a site menu)

The extension is able to modify the Accept headers on the request. You should get the file type corresponding to the file extension.

(2) right-click > Copy Image, then in Windows File Explorer, right-click a blank area > Paste

The extension is able to modify the Accept headers on the request. You should get the file type corresponding to the file extension.

(3) Drag and drop

When dragging, the new request apparently bypasses my extension so you get whatever the server prefers to send. My extension is not intentionally ignoring any requests, so I don't know why it doesn't see these. ??

(4) right-click > View Image Info > Save As [works without the extension]

Perhaps due to a bug, when re-requesting from this dialog, Firefox does not signal the server that it accepts webp, so the extension doesn't need to modify the Accept header (if it even sees this request). You should get the file type corresponding to the file extension.

**Comment by BMWBig6** [comment]
Thanks for verifying what I was observing on my end too.  I wasn't sure there was any rhyme or reason and assumed it was server-specific, but your testing of the different file save methods shows that Firefox seems to behave differently depending on the method used.  Drag-and-drop is very convenient but I will try the other methods if they are more reliable in pulling JPGs.

**Comment by jscher2000** [comment]
I filed a bug for this in January, but no progress so far. I'm going to close this issue as it's out of my control.

https://bugzilla.mozilla.org/show_bug.cgi?id=1684957
