### ISSUE TITLE
Causes issues with the "Load Reddit Images Directly" extension

### ISSUE THREAD

**Issue by SigmaTheDJ** [jscher2000/dont-accept-webp#10]
This is the extension I'm referring to: -

https://addons.mozilla.org/en-US/firefox/addon/load-reddit-images-directly/

With both extensions enabled, the Reddit one sometimes stops working and only starts working again if you disable it, then re-enable it. However, if the WebP one is disabled and only the Reddit one is enabled, the Reddit one works fine.

If you add an exception for Reddit in the WebP extension, the issue also goes away, so that's one way to use both extensions at the same time.

I don't know if this is a bug with your extension or not, but I thought it was worth reporting it to you anyway.

**Comment by jscher2000** [comment]
Hi, thank you for reporting this.

It looks like there is a direct conflict because the other extension expressly sets the accept header to allow AVIF and WEBP as of version 1.1 in early July:

https://github.com/nopperl/load-reddit-images-directly/blob/main/background.js

I think that means that the installation/load order determines which one wins, which definitely can lead to inconsistent results.

Maybe my add-on can detect when the other add-on is installed using the [management API](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/management) and automatically make exceptions for its list of sites:

urls: ['*://i.redd.it/*', '*://external-preview.redd.it/*', '*://preview.redd.it/*']

I've never tried that before and don't know how reliable it is.

**Comment by SigmaTheDJ** [comment]
Many thanks for the response. TBH, I'm perfectly happy with my solution of just excluding Reddit from your extension, but I have encountered a couple of other people who had the same issue as me, but didn't figure out the cause, so if you could find a way to address it, that would be great. :)

**Comment by jscher2000** [comment]
The update to automatically detect this add-on and step back from changes to the domains *it* handles has finally been approved.

There is a permission dialog associated with the update, which could affect adoption. Perhaps I should have made it optional? Oh well...

![management-permission-0 9](https://github.com/jscher2000/dont-accept-webp/assets/8264646/8ea9b089-dfa2-400f-80ff-e4a5d3cb72fa)

**Comment by SigmaTheDJ** [comment]
Excellent, thanks!

**Comment by nopperl** [comment]
@jscher2000 thanks for fixing this conflict within your extension! Just to give an information on why my extension uses this explicit accept header: it's using the default Firefox values from https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values#values_for_an_image.

I think the current fix is a good solution; if there are any further conflicts I could also change the accept header to the non-conventional `image/*` again.

**Comment by jscher2000** [comment]
Oh hey, thanks for visiting. 

> I think the current fix is a good solution; if there are any further conflicts I could also change the accept header to the non-conventional `image/*` again.

I don't think you need to do that. It's just so hard to test the interaction that it's simpler to make exceptions as problems arise.

**Comment by sdrapha** [comment]
> The update to automatically detect this add-on and step back from changes to the domains _it_ handles has finally been approved.
> 
> There is a permission dialog associated with the update, which could affect adoption. Perhaps I should have made it optional? Oh well...
> 
> ![management-permission-0 9](https://user-images.githubusercontent.com/8264646/281459262-8ea9b089-dfa2-400f-80ff-e4a5d3cb72fa.png)

I did got a little suspicious when I saw that warning without the context of why the change. 
So that is how I found this issue, because I was investigating what changed in the code before I accepted the warning message, and I'm not affected by the issue since I never had that other extension. 
So, yes, maybe that should have been optional to not scare people away from installing the extension, or maybe not, I don't know. Just sharing my experience, this time I had time to investigate. If not, I could have droped the whole thing just to be on the safe side.

**Comment by jscher2000** [comment]
Yes, with the benefit of hindsight, I should have shown a notification of a new feature available with an optional permission. But so it goes when you're doing everything for the first time. At this point, I think I'll just leave it as it is.
